Repository PrestaShopCorp/partner-devtools.prestashop.com, pull requests merged in 2021-12, with the labels that each got.

#8 build: update account lib & service container
  modules/rbm_example/composer.json
  modules/rbm_example/composer.lock
Labels: PHP

#7 build: update account vue
  modules/rbm_example/_dev/apps/package-lock.json
  modules/rbm_example/_dev/apps/package.json
  modules/rbm_example/_dev/apps/yarn.lock
Labels: VueJS

#9 build(dependencies): update to laste version
  modules/rbm_example/_dev/LICENSE
  modules/rbm_example/_dev/apps/LICENSE
  modules/rbm_example/_dev/apps/package.json
  modules/rbm_example/_dev/apps/yarn.lock
  modules/rbm_example/_dev/package.json
Labels: enhancement
